### ISSUE TITLE
Use DbContext rather than a second abstraction in order to be able to use constructor with DbContextOptions

### ISSUE THREAD

**Issue by hubo0831** [cleancodelabs/EntityFrameworkCore.GenericRepository#1]

**Comment by alsami** [comment]
For what do you need those options, when having the need to implement `DbContextOptionsBuilder` like required from the [base-context](https://github.com/cleancodelabs/EntityFrameworkCore.GenericRepository/blob/5f88b6316cf7f1d92f2078e1da5bfa162b69de1a/src/EntityFrameworkCore.GenericRepository/GenericRepositoryContext.cs#L7)?

Secondly you need to derive from that abstract context and you can add that constructor yourself.

**Comment by hubo0831** [comment]
I want to inject DbContextOptions, but not write hard code,GenericRepositoryContext has no constructor with DbContextOptions,   i can't use.

**Comment by alsami** [comment]
You can add one in the derived class

```csharp
public class MyDbContext : GenericRepositoryContext
{
   public MyDbContext(DbContextOptions options)
   {
      OnConfiguring(new DbContextOptionsBuilder(options));
   }

     protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
     {
         optionsBuilder.UseInMemoryDatabase("InMemoryTestDb");
      }
}
```

Will change that with version 3 but that will introduce breaking changes.

**Comment by hubo0831** [comment]
MyDbContext don't need to depend on database e.g. memorydb, database options is injected, it is configed by user. Don't use OnConfiguring method, it depend on database .

**Comment by alsami** [comment]
This has been implemented now. You can now just derive from `DbContext` and implement what ever you want.

**Comment by hubo0831** [comment]
OK, thanks!
